version: "2.3"

services:

  editor:
    image: ${IMAGE_NAME:-approov/shipfast-android-studio}:${ENVIRONMENT:-dev}_${ANDROID_STUDIO_VERSION:? Missing ANDROID_STUDIO_VERSION}
    build:
      context: ./docker/build
      dockerfile: editor.Dockerfile
      args:
        ANDROID_STUDIO_BUILD: "${ANDROID_STUDIO_BUILD:? Missing ANDROID_STUDIO_BUILD}"
        ANDROID_STUDIO_VERSION: "${ANDROID_STUDIO_VERSION:? Missing ANDROID_STUDIO_VERSION}"
    container_name: "${ENVIRONMENT:-dev}.editor"
    hostname: "${ENVIRONMENT:-dev}.editor"
    env_file:
      - .env
    environment:
      XAUTHORITY: /tmp/.docker.X11-unix
      DISPLAY: "${DISPLAY:-0:}"
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PROJECT_HOST_DIR}/.docker.X11-unix:/tmp/.docker.X11-unix
      - ${PROJECT_HOST_DIR}/android-studio/${ANDROID_STUDIO_MAJOR_VERSION:? Missing ANDROID_STUDIO_VERSION}/${PROJECT_NAME}/.AndroidStudio${ANDROID_STUDIO_MAJOR_VERSION:? Missing ANDROID_STUDIO_VERSION}:/home/developer/.AndroidStudio${ANDROID_STUDIO_MAJOR_VERSION:? Missing ANDROID_STUDIO_VERSION}
      - ${PROJECT_HOST_DIR}/android-studio/${ANDROID_STUDIO_MAJOR_VERSION:? Missing ANDROID_STUDIO_VERSION}/${PROJECT_NAME}/Android:/home/developer/Android
      - ${PROJECT_HOST_DIR}/android-studio/${ANDROID_STUDIO_MAJOR_VERSION:? Missing ANDROID_STUDIO_VERSION}/${PROJECT_NAME}/.android:/home/developer/.android
      - ${PROJECT_HOST_DIR}/android-studio/${ANDROID_STUDIO_MAJOR_VERSION:? Missing ANDROID_STUDIO_VERSION}/${PROJECT_NAME}/.gradle:/home/developer/.gradle
      - ${PROJECT_HOST_DIR}/android-studio/${ANDROID_STUDIO_MAJOR_VERSION:? Missing ANDROID_STUDIO_VERSION}/${PROJECT_NAME}/.java:/home/developer/.java
      - ${PROJECT_HOST_DIR}/.mitmproxy:/home/developer/.mitmproxy
      - ${ANDROID_APP_DIR:-./}:/home/developer/workspace
    networks:
      - shipfast

  api:
    image: approov/shipfast-nodejs:${ENVIRONMENT:-dev}
    build:
      context: ./docker/build
      dockerfile: nodejs.Dockerfile
    container_name: "${ENVIRONMENT:-dev}.api"
    hostname: "${ENVIRONMENT:-dev}.api"
    working_dir: /home/node/workspace/server/shipfast-api
    env_file:
      - ./.env
    volumes:
      - ./:/home/node/workspace
    command:
      - npm
      - start
    networks:
      - shipfast
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${ENVIRONMENT:-dev}.shipfast-api"
      - "traefik.docker.network=traefik"
      - "traefik.port=${SHIPFAST_HTTP_PORT}"
      - "traefik.frontend.rule=Host:${SHIPFAST_PUBLIC_DOMAIN:-localhost}"

  web:
    image: approov/shipfast-nodejs:${ENVIRONMENT:-dev}
    build:
      context: ./docker/build
      dockerfile: nodejs.Dockerfile
    container_name: "${ENVIRONMENT:-dev}.web"
    hostname: "${ENVIRONMENT:-dev}.web"
    working_dir: /home/node/workspace/server/shipraider-rogue-web
    env_file:
      - .env
    volumes:
      - ./:/home/node/workspace
    command:
      - npm
      - start
    networks:
      - shipfast
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${ENVIRONMENT:-dev}.shipraider-web"
      - "traefik.docker.network=traefik"
      - "traefik.port=${SHIPRAIDER_HTTP_PORT}"
      - "traefik.frontend.rule=Host:${SHIPRAIDER_PUBLIC_DOMAIN:-localhost}"

networks:
  shipfast:
    driver: "bridge"
  traefik:
    external: true
