version: "2.1"

services:

  shipfast-demo:
    image: ${IMAGE_NAME:-approov/shipfast-demo}
    build:
      context: docker/build
    env_file:
      - .env
    devices:
      - /dev/dri:/dev/dri
      - /dev/kvm:/dev/kvm
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.docker-android-studio/${PROJECT_HOST_DIR}/.AndroidStudio3.2:/home/mobile/.AndroidStudio3.2
      - ~/.docker-android-studio/${PROJECT_HOST_DIR}/Android:/home/mobile/Android
      - ~/.docker-android-studio/${PROJECT_HOST_DIR}/.android:/home/mobile/.android
      - ~/.docker-android-studio/${PROJECT_HOST_DIR}/.gradle:/home/mobile/.gradle
      - ~/.docker-android-studio/${PROJECT_HOST_DIR}/.java:/home/mobile/.java
      - ${ANDROID_APP_DIR:-./}:/home/mobile/AndroidStudioProjects
      - ${DEMO_SETUP_DIR:-./docker/build/setup}:/demo/ssl
      - ${NODE_DIR:-./server}:/home/mobile/app
      - ~/.docker-mobile-demo/${PROJECT_HOST_DIR}/mitmproxy:/home/mitmproxy/.mitmproxy
      #- ./docker/build/.mozilla:/home/mobile/.mozilla
    networks:
      - mobile_demo_network

networks:
  mobile_demo_network:
    driver: "bridge"
