#!/bin/bash

set -eu

Show_Help() {
    printf "\nSHIPFAST API PROTECTION DEMO\n"

    printf "\n Servers:\n"
    printf "\t./shipfast up servers\n"
    printf "\t./shipfast logs servers\n"
    printf "\t./shipfast restart servers\n"
    printf "\t./shipfast down servers\n"

    printf "\n Shipfast API:\n"
    printf "\t./shipfast up api\n"
    printf "\t./shipfast logs api\n"
    printf "\t./shipfast restart api\n"
    printf "\t./shipfast down api\n"

    printf "\n Shipraider Web:\n"
    printf "\t./shipfast up web\n"
    printf "\t./shipfast logs web\n"
    printf "\t./shipfast restart web\n"
    printf "\t./shipfast down web\n"

    printf "\n Android Studio:\n"
    printf "\t./shipfast up editor\n"
    printf "\t./shipfast logs editor\n"
    printf "\t./shipfast restart editor\n"
    printf "\t./shipfast down editor\n"

    printf "\n Cache:\n"
    printf "\t./shipfast cache api delete v1 authorization-token-here\n"

    printf "\n Proxy:\n"
    printf "\t./shipfast proxy -p 8000\n"

    printf "\n Logs:\n"
    printf "\t./shipfast logs\n"
    printf "\t./shipfast logs -f \n"
    printf "\t./shipfast logs --follow \n"
    printf "\t./shipfast logs -t 100 \n"
    printf "\t./shipfast logs --tail 100 \n"
    printf "\t./shipfast logs -f -t 100 \n"
    printf "\t./shipfast logs -f -t 100 api \n"
    echo
}

Docker_Container_Is_Running() {
  sudo docker container ls -a | grep -q "${1? Missing container name.}" -

  return $?
}

Build_Api_Server() {
    ${DOCKER_COMPOSE} build api
}

Build_Editor() {
    ${DOCKER_COMPOSE} build editor
    ./docker/setup/docker-volumes-dirs.sh "${PROJECT_NAME}" "${PROJECT_HOST_DIR}" "${ANDROID_STUDIO_MAJOR_VERSION}"
}

Build_Web_Server() {
    ${DOCKER_COMPOSE} build web
}

Start_Editor() {

    local _ca_crt_file="./docker/demo/setup/certificates/ProxyCA.crt"
    local _ca_pem_dir="/etc/ssl/certs"
    local _ca_pem_filename="ProxyCA.pem"
    local _ca_pem_file="${_ca_pem_dir}/${_ca_pem_filename}"
    local _ca_name="ProxyCA"

    ./docker/setup/docker-volumes-dirs.sh "${PROJECT_NAME}" "${PROJECT_HOST_DIR}" "${ANDROID_STUDIO_MAJOR_VERSION}"

    # KVM needs to change permissions in order for Android Studio can work.
    # For some reason the permissions return to original state after we close the editor
    # TODO: find a permanent solution
    ${ROOT_PREFIX} chown ${_USER}:${_USER} /dev/kvm

    ${DOCKER_COMPOSE} up -d editor

    if [ ! -f "${APPROOV_SDK_PATH}" ]; then
        printf "\n---> WARNING: Missing file ${APPROOV_SDK_PATH} <---\n"
        printf "Note: This can be ignored until you need to build the 'approov' product flavour\n"
        printf "\n---> ADD FILE WITH: approov sdk ./path/to/dev.token -getLibrary ${APPROOV_SDK_PATH} <---\n"
        printf "\n---> APPROOV CONFIG: approov sdk ./path/to/dev.token -getConfig .approov-initial.config <---\n"
        printf "\n---> Add the Approov initial config to the strings resource file. <---\n\n"
    fi
}

Restart_Editor() {
    Destroy_Editor && Start_Editor
}

Destroy_Editor() {
    ${DOCKER_COMPOSE} stop editor
    ${DOCKER_COMPOSE} rm -f editor
}

Start_Api_Server() {

    # From the android emulator we must use 10.0.2.2:3333 to call localhost

    if [ ! -d "./server/shipfast-api/node_modules" ]; then
        ${DOCKER_COMPOSE} run api sh -c 'npm install && exit || exit'
    fi

    ${DOCKER_COMPOSE} up -d api
}

Restart_Api_Server() {
    Destroy_Api_Server && Start_Api_Server
}

Destroy_Api_Server() {
    ${DOCKER_COMPOSE} stop api
    ${DOCKER_COMPOSE} rm -f api
}

Start_Web_Server() {

    if [ ! -d "./server/shipraider-rogue-web/node_modules" ]; then
        ${DOCKER_COMPOSE} run web sh -c 'npm install && exit || exit'
    fi

    ${DOCKER_COMPOSE} up -d web
}

Restart_Web_Server() {
    Destroy_Web_Server && Start_Web_Server
}

Destroy_Web_Server() {
    ${DOCKER_COMPOSE} stop web
    ${DOCKER_COMPOSE} rm -f web
}

Logs() {
    ${DOCKER_COMPOSE} logs ${@}
}

Run_Shell() {
    local docker_compose_service="${1? Missing docker composer service name.}"
    local shell="${2? Missing shell to use, e.g: zsh}"
    shift 2

    local container_name="dev.${docker_compose_service}"

    if Docker_Container_Is_Running "${container_name}"; then
        ${DOCKER_COMPOSE} exec "${docker_compose_service}" "${shell}" ${@}
        return
    fi

    ${DOCKER_COMPOSE} run --rm "${docker_compose_service}" "${shell}" ${@}
}

Start_Proxy() {
    ${DOCKER_COMPOSE} exec editor mitmproxy ${@}
}

Main() {

    local ROOT_PREFIX=""

    local DOCKER_COMPOSE=$(which docker-compose)

    local _USER="$(id -un)"

    local LINES=""

    local ANDROID_STUDIO_BUILD="192.6241897"
    local ANDROID_STUDIO_VERSION=3.6.1.0
    local ANDROID_STUDIO_MAJOR_VERSION=3.6

    local PROJECT_DIR="${PWD#*${HOME}/}"
    local PROJECT_NAME="${PROJECT_DIR//\//_}"

    #PROJECT_HOST_DIR="${HOME}/.docker-shipfast-demo/${PROJECT_NAME//\//_}"
    local PROJECT_HOST_DIR="${HOME}/.docker-shipfast-demo"

    # Auto detect if we need to use sudo
    if type sudo &> /dev/null; then
        ROOT_PREFIX=sudo
    fi

    # Sometimes we may have sudo in our system, but to run `docker-compose` it
    #  will not find the executable with sudo, I am looking at you AWS EC2, thus
    #  we can customize it.
    if [ -f ./.shipfast.local.vars ]; then
        source ./.shipfast.local.vars
    fi

    DOCKER_COMPOSE="${ROOT_PREFIX} ${DOCKER_COMPOSE}"

    if [ ! -f ./.env ]; then
        printf "\n---> FATAL ERROR: Missing .env file <---\n"
        exit 1
    fi

    local APPROOV_SDK_PATH=./app/android/kotlin/ShipFast/approov/approov.aar

    # Setup X11 server authentication
    # @link https://wiki.ros.org/docker/Tutorials/GUI#The_isolated_way
    if type xauth &> /dev/null; then
        local _XAUTH="${PROJECT_HOST_DIR}"/.docker.X11-unix
        touch "${_XAUTH}"
        xauth nlist "${DISPLAY}" | sed -e 's/^..../ffff/' | xauth -f "${_XAUTH}" nmerge -
    fi

    # Updates the env var PROJECT_NAME
    if grep -q "PROJECT_NAME" .env && ! grep -q "${PROJECT_NAME}" .env
        then
            while IFS= read -r line
            do
                case "${line}" in
                   "PROJECT_NAME"*) LINES="${LINES}PROJECT_NAME=${PROJECT_NAME}\n" ;;
                   *) LINES="${LINES}${line}\n" ;;
                esac
            done < .env

            if [ ! -z ${LINES} ]
                then
                    printf "${LINES}" > .env
            fi
    fi

    # Updates the env var PROJECT_HOST_DIR
    if grep -q "PROJECT_HOST_DIR" .env && ! grep -q "${PROJECT_HOST_DIR}" .env
        then
            while IFS= read -r line
            do
                case "${line}" in
                   "PROJECT_HOST_DIR"*) LINES="${LINES}PROJECT_HOST_DIR=${PROJECT_HOST_DIR}\n" ;;
                   *) LINES="${LINES}${line}\n" ;;
                esac
            done < .env

            if [ ! -z ${LINES} ]
                then
                    printf "${LINES}" > .env
            fi
    fi

    # Creates the env var PROJECT_NAME
    if ! grep -q "${PROJECT_NAME}" .env
        then
            printf "\nPROJECT_NAME=${PROJECT_NAME}\n" >> .env
    fi

    # Creates the env var PROJECT_HOST_DIR
    if ! grep -q "${PROJECT_HOST_DIR}" .env
        then
            printf "\nPROJECT_HOST_DIR=${PROJECT_HOST_DIR}\n" >> .env
    fi

    local ANDROID_SDK_DIR="${PROJECT_HOST_DIR}/android-studio/${ANDROID_STUDIO_MAJOR_VERSION}/${PROJECT_NAME}/Android/Sdk"

    for input in  "${@}"; do
        case "${input}" in
            -h | --help | help )
                Show_Help
                exit $?
            ;;

            build )
                case "${2:-}" in
                    api )
                        Build_Api_Server
                    ;;

                    editor )
                        Build_Editor
                    ;;

                    servers )
                        Build_Api_Server
                        Build_Web_Server
                    ;;

                    web )
                        Build_Web_Server
                    ;;

                    * )
                        Show_Help
                    ;;
                esac

                exit $?
            ;;

            cache )
                case "${2:-}" in
                    api )
                        shift 2
                        ./server/shipfast-api/bin/cache.sh "${@}"
                        exit $?
                    ;;
                esac

                exit $?
            ;;


            down )
                case "${2:-}" in
                    api )
                        Destroy_Api_Server
                    ;;

                    editor )
                        Destroy_Editor
                    ;;

                    servers )
                        Destroy_Api_Server
                        Destroy_Web_Server
                    ;;

                    web )
                        Destroy_Web_Server
                    ;;

                    * )
                        Show_Help
                    ;;
                esac

                exit $?
            ;;

            logs )
                shift 1
                Logs ${@}
                exit $?
            ;;

            proxy )
                shift 1
                Start_Proxy "${@}"
                exit $?
            ;;

            restart )
                case "${2:-}" in
                    api )
                        Restart_Api_Server
                    ;;

                    editor )
                        Restart_Editor
                    ;;

                    servers )
                        Restart_Api_Server
                        Restart_Web_Server
                    ;;

                    web )
                        Restart_Web_Server
                    ;;

                    * )
                        Show_Help
                    ;;
                esac

                exit $?
            ;;

            shell )
                shift 1
                Run_Shell ${@}
                exit $?
            ;;

            up )
                case "${2:-}" in
                    api )
                        Start_Api_Server
                    ;;

                    editor )
                        Start_Editor
                    ;;

                    servers )
                        Start_Api_Server
                        Start_Web_Server
                    ;;

                    web )
                        Start_Web_Server
                    ;;

                    * )
                        Show_Help
                    ;;
                esac

                exit $?
            ;;

        esac
    done

    Show_Help

    exit $?
}

Main ${@}
